#---------------------------------#
#    environment configuration    #
#---------------------------------#

skip_branch_with_pr: true

# Build worker image (VM template)
image:
  - Ubuntu2004
  - Visual Studio 2019
  - macos

# set clone depth
clone_depth: 5                      # clone entire repository history if not defined

# There is no building process
build: off

# scripts that run after cloning repository
install:
  - sh: if [[ $CI_LINUX == true ]]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; bash miniconda.sh -b -p $HOME/miniconda; export PATH="$HOME/miniconda/bin:$PATH"; else curl https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -L -o miniconda.sh; bash miniconda.sh -b -p $HOME/miniconda; export PATH="$HOME/miniconda/bin:$PATH"; fi
  - sh: hash -r
  - sh: source activate
  - cmd: SET MINICONDA_PATH="C:\\Miniconda38-x64"
  - cmd: SET PATH=%MINICONDA_PATH%;%MINICONDA_PATH%"\\Scripts";%PATH%
  - cmd: conda init cmd.exe
  - conda config --set always_yes yes --set changeps1 no
  - conda config --set auto_update_conda no
  
  # Set environment variables  
  - sh: BIONC_FOLDER=`pwd`
  - cmd: SET BIONC_FOLDER=%cd%
  
  # Setup the conda environment
  - conda env update -f environment.yml -n base
  - conda install pytest-cov black pytest codecov -cconda-forge
  - conda list
  - sh: if [[ $CI_LINUX == true ]]; then black . -l120 --exclude "external/*" --check; fi

# to run your custom scripts instead of automatic tests
test_script:
  - pytest -v --color=yes --cov-report term-missing --cov=bionc tests
  - python setup.py install
  - sh: cd
  - cmd: cd C:/
  - conda list
  # python version check
  - python --version
  # print the environment variables from which python is called
  - python -c "import os; print(os.environ)"
  - python -c "import bionc"
  - sh: cd $BIONC_FOLDER
  - cmd: cd %BIONC_FOLDER%


#---------------------------------#
#        global handlers          #
#---------------------------------#

# on successful build
on_success:
  - sh: if [[ $CI_MACOS == true ]]; then codecov; fi

